version: '3.5'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: microservices_sqlserver
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: abcDEF123#

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: microservices_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  product-microservice:
    depends_on:
      - sqlserver
      - rabbitmq
    build:
      context: ./
      dockerfile: Product.Microservice/Dockerfile
    image: product-microservice
    container_name: microservices_product
    links:
      - sqlserver
      - rabbitmq
    ports:
      - 5003:5003

  customer-microservice:
    depends_on:
      - sqlserver
      - rabbitmq
    build:
      context: ./
      dockerfile: Customer.Microservice/Dockerfile
    image: customer-microservice
    container_name: microservices_customer
    links:
      - sqlserver
      - rabbitmq
    ports:
      - 5005:5005

  gateway:
    build:
      context: ./
      dockerfile: Gateway.WebApi/Dockerfile
    image: gateway-for-microservice
    container_name: microservices_gateway
    links:
      - sqlserver
      - rabbitmq
    ports:
      - 5007:5007
